# Site settings
title: Adrià Martí
description: My page
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Adrià Martí
user_description: Young network engineer with a Bachelor's and Master's Degree in Network Engineering at Universitat Politècnica de Catalunya. Developing code in Javascript, Java, C# and Python since 2017. My passion for virtualization, automatization and coding have lead me to an increasing hunger for new tools and techniques, resulting in several projects where I apply my newest skills whereas I keep the older ones updated.
user_title: Network Engineer
email: adriml96@gmail.com
linkedin_username: adrià-martí-luque-10306b130
github_username: AMarti96

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']